CREATE TABLE `Alcohols` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE,
	`Rank`	TEXT NOT NULL
);
CREATE TABLE `Coctails` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RecipeId`	INTEGER NOT NULL,
	`Name`	TEXT NOT NULL,
	`Quantity`	TEXT NOT NULL,
	`Cost`	INTEGER NOT NULL,
	`Type`	INTEGER NOT NULL
);
CREATE TABLE `Recipes` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RecipeId`	INTEGER NOT NULL,
	`AlcoId`	INTEGER NOT NULL,
	`Part`	TEXT NOT NULL
);
CREATE TABLE `sqlite_sequence` (
	`name`	TEXT,
	`seq`	TEXT
);